name: helping_hand
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+0.1.1

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.6.5
  device_info_plus: ^11.3.0
  dotlottie_loader: ^0.0.4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_geofire:
    path: packages/flutter_geofire
  flutter_overlay_window: ^0.4.5
  flutter_spinkit: ^5.2.1
  flutter_udid: ^4.0.0
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  google_maps_flutter_android: ^2.14.13
  google_maps_flutter_platform_interface: ^2.11.1
  http: ^1.3.0
  lottie: ^3.1.2
  page_transition: ^2.2.1
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "media/image/hh-logo.png"
  min_sdk_android: 21



flutter:
  uses-material-design: true
  assets: 
    - media/
    - media/image/
    - media/anims/